include = ["Cargo.toml", "**/*.toml"]
# EN: Specifies which files the formatting rules should apply to.
# KO: 포맷팅 규칙이 적용될 파일들을 지정합니다.

[formatting]
# EN: Groups all formatting-related settings.
# KO: 포맷팅 관련 설정들을 그룹화하는 섹션입니다.

# EN: Align consecutive entries vertically.
# KO: 연속된 항목들을 수직으로 정렬합니다.
align_entries = false

# EN: Append trailing commas for multi-line arrays.
# KO: 여러 줄에 걸친 배열의 마지막에 쉼표를 추가합니다.
array_trailing_comma = true

# EN: Expand arrays to multiple lines that exceed the maximum column width.
# KO: 최대 열 너비를 초과하는 배열을 여러 줄로 확장합니다.
array_auto_expand = true

# EN: Collapse arrays that don't exceed the maximum column width and don't contain comments.
# KO: 최대 열 너비를 초과하지 않고 주석이 없는 배열은 한 줄로 축소합니다.
array_auto_collapse = true

# EN: Omit white space padding from single-line arrays.
# KO: 한 줄 배열에서 공백 패딩을 생략합니다.
compact_arrays = true

# EN: Omit white space padding from the start and end of inline tables.
# KO: 인라인 테이블의 시작과 끝에서 공백 패딩을 생략합니다.
compact_inline_tables = false

# EN: Maximum column width in characters, affects array expansion and collapse, this doesn't take whitespace into account.
# EN: Note that this is not set in stone, and works on a best-effort basis.
# KO: 최대 열 너비(문자 수)로, 배열 확장 및 축소에 영향을 줍니다. 이는 공백을 고려하지 않습니다.
# KO: 참고로 이 값은 절대적인 것이 아니라 최선의 노력을 기반으로 작동합니다.
column_width = 80

# EN: Indent based on tables and arrays of tables and their subtables, subtables out of order are not indented.
# KO: 테이블, 테이블 배열 및 하위 테이블을 기준으로 들여쓰기 합니다. 순서가 맞지 않는 하위 테이블은 들여쓰기 되지 않습니다.
indent_tables = false

# EN: The substring that is used for indentation, should be tabs or spaces (but technically can be anything).
# KO: 들여쓰기에 사용되는 문자열로, 탭이나 공백이어야 합니다(기술적으로는 어떤 것이든 가능).
indent_string = '  '

# EN: Add trailing newline at the end of the file if not present.
# KO: 파일 끝에 개행 문자가 없으면 추가합니다.
trailing_newline = true

# EN: Alphabetically reorder keys that are not separated by empty lines.
# KO: 빈 줄로 구분되지 않은 키들을 알파벳 순으로 재정렬합니다.
reorder_keys = true

# EN: Maximum amount of allowed consecutive blank lines. This does not affect the whitespace at the end of the document, as it is always stripped.
# KO: 허용되는 최대 연속 빈 줄 수입니다. 문서 끝의 공백은 항상 제거되므로 이 설정의 영향을 받지 않습니다.
allowed_blank_lines = 1

# EN: Use CRLF for line endings.
# KO: 줄 끝에 CRLF를 사용합니다(false로 설정되어 있으므로 LF 사용).
crlf = false
